# proto-file: google/cloud/cloudaicompanion/anarres/v1main/service.proto
# proto-message: SchemaDetails

tables: {
  table: "allowances"
  columns: {
    column: "allowance_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "allowance"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "allowance_description"
    data_type: "text"
  }
}
tables: {
  table: "attendance"
  columns: {
    column: "attendance_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "check_in_time"
    data_type: "time DEFAULT NULL"
  }
  columns: {
    column: "check_out_time"
    data_type: "time DEFAULT NULL"
  }
  columns: {
    column: "check_in_location"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "check_out_location"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "check_in_method"
    data_type: "char(100) DEFAULT NULL"
  }
  columns: {
    column: "check_out_method"
    data_type: "char(100) DEFAULT NULL"
  }
  columns: {
    column: "work_hours"
    data_type: "decimal(10,2) DEFAULT NULL"
  }
  columns: {
    column: "overtime_hours"
    data_type: "decimal(10,2) DEFAULT NULL"
  }
  columns: {
    column: "shift"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "notes"
    data_type: "text"
  }
}
tables: {
  table: "benefit"
  columns: {
    column: "benefit_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "benefit_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "description"
    data_type: "text"
  }
  columns: {
    column: "coverage"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "provider"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "eligibility_criteria"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "usage_instructions"
    data_type: "text"
  }
  columns: {
    column: "contact_info"
    data_type: "varchar(255) DEFAULT NULL"
  }
}
tables: {
  table: "company"
  columns: {
    column: "company_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "company_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "industry"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "size"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "location"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "website"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "contact_person"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "contact_email"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "contact_phone"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "founded_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "ownership_type"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "social_media_facebook"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "social_media_instagram"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "social_media_linkedin"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "social_media_x"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "clients"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "products"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "partners"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "competitors"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "financial_year_end"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "department"
  columns: {
    column: "department_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "department_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "manager_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "budget"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "is_active"
    data_type: "tinyint(1) DEFAULT NULL"
  }
  columns: {
    column: "goals"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "achievements"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "company_id"
    data_type: "int DEFAULT NULL"
  }
}
tables: {
  table: "employee_allowances"
  columns: {
    column: "employee_allowance_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "allowance_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "type"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "amount"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "effective_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "date_created"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "employee_business_expense"
  columns: {
    column: "expense_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "expense_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "expense_category"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "expense_description"
    data_type: "text"
  }
  columns: {
    column: "expense_amount"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "expense_receipt"
    data_type: "varchar(255) DEFAULT NULL"
  }
}
tables: {
  table: "employee_certification"
  columns: {
    column: "certification_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "certification_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "issuing_organization"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "issue_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "expiration_date"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "employee_computer"
  columns: {
    column: "computer_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "computer_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "serial_number"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "model"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "purchase_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "warranty_expiry_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "status"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "assigned_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "returned_date"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "employee_termination"
  columns: {
    column: "termination_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "termination_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "reason"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "description"
    data_type: "text"
  }
}
tables: {
  table: "employee_training"
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "training_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "employee_travel"
  columns: {
    column: "travel_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "travel_purpose"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "travel_destination"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "travel_start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "travel_end_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "travel_expenses"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
}
tables: {
  table: "employee_x_benefit"
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "benefit_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "employee"
  columns: {
    column: "employee_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "first_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "last_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "email"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "phone_number"
    data_type: "varchar(20) DEFAULT NULL"
  }
  columns: {
    column: "address"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "image_url"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "date_of_birth"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "gender"
    data_type: "varchar(10) DEFAULT NULL"
  }
  columns: {
    column: "marital_status"
    data_type: "varchar(20) DEFAULT NULL"
  }
  columns: {
    column: "national_identification"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "bank_account_number"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "emergency_contact_name"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "emergency_contact_number"
    data_type: "varchar(20) DEFAULT NULL"
  }
  columns: {
    column: "contract_type"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "hire_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "department_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "job_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "manager_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "company_id"
    data_type: "int DEFAULT NULL"
  }
}
tables: {
  table: "holiday"
  columns: {
    column: "Date"
    data_type: "date NOT NULL"
  }
  columns: {
    column: "Day"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "Occasion"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "Geographic_location"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "City"
    data_type: "varchar(255) NOT NULL"
  }
  columns: {
    column: "Project"
    data_type: "varchar(255) NOT NULL"
  }
}
tables: {
  table: "invoice"
  columns: {
    column: "invoice_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "invoice_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "due_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "total_amount"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "status"
    data_type: "varchar(50) DEFAULT NULL"
  }
}
tables: {
  table: "job_history"
  columns: {
    column: "job_history_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "job_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "department_id"
    data_type: "int DEFAULT NULL"
  }
}
tables: {
  table: "job"
  columns: {
    column: "job_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "job_title"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "job_description"
    data_type: "text"
  }
  columns: {
    column: "skills_required"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "skills_preferred"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "min_salary"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "max_salary"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "department_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "responsibilities"
    data_type: "text"
  }
  columns: {
    column: "benefits"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "education_requirements"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "experience_requirements"
    data_type: "json DEFAULT NULL"
  }
  columns: {
    column: "employment_type"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "location"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "vacancies"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "status"
    data_type: "varchar(50) DEFAULT NULL"
  }
}
tables: {
  table: "leave_request"
  columns: {
    column: "leave_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "leave_type"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "status"
    data_type: "varchar(50) DEFAULT 'Pending'"
  }
  columns: {
    column: "duration"
    data_type: "decimal(10,2) DEFAULT NULL"
  }
  columns: {
    column: "reason"
    data_type: "text"
  }
  columns: {
    column: "approval_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "rejection_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "comments"
    data_type: "text"
  }
  columns: {
    column: "attachment"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "processed_by"
    data_type: "int DEFAULT NULL"
  }
}
tables: {
  table: "manager"
  columns: {
    column: "manager_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
}
tables: {
  table: "payment"
  columns: {
    column: "payment_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "payment_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "amount"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "payment_method"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "invoice_id"
    data_type: "int DEFAULT NULL"
  }
}
tables: {
  table: "performance_review"
  columns: {
    column: "review_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "reviewer_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "review_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "performance_rating"
    data_type: "decimal(5,2) DEFAULT NULL"
  }
  columns: {
    column: "comments"
    data_type: "text"
  }
}
tables: {
  table: "salary"
  columns: {
    column: "salary_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "salary"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "start_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "end_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "currency"
    data_type: "varchar(10) DEFAULT NULL"
  }
  columns: {
    column: "pay_frequency"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "bonus"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "taxes"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "deductions"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "total_compensation"
    data_type: "decimal(15,2) DEFAULT NULL"
  }
  columns: {
    column: "status"
    data_type: "varchar(50) DEFAULT NULL"
  }
}
tables: {
  table: "timesheet_employee"
  columns: {
    column: "timesheet_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "employee_id"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "Month"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "Year"
    data_type: "int DEFAULT NULL"
  }
  columns: {
    column: "Fort_Night1_flag"
    data_type: "tinyint(1) DEFAULT NULL"
  }
  columns: {
    column: "Fort_Night2_flag"
    data_type: "tinyint(1) DEFAULT NULL"
  }
}
tables: {
  table: "timesheet"
  columns: {
    column: "timesheet_id"
    data_type: "int NOT NULL DEFAULT '0'"
  }
  columns: {
    column: "Date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "Working_hours"
    data_type: "decimal(10,2) DEFAULT NULL"
  }
  columns: {
    column: "Overtime"
    data_type: "decimal(10,2) DEFAULT NULL"
  }
  columns: {
    column: "Leave_type"
    data_type: "varchar(255) DEFAULT NULL"
  }
}
tables: {
  table: "training"
  columns: {
    column: "training_id"
    data_type: "int NOT NULL"
  }
  columns: {
    column: "title"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "description"
    data_type: "text"
  }
  columns: {
    column: "date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "location"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "link"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "trainer"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "duration"
    data_type: "decimal(10,2) DEFAULT NULL"
  }
  columns: {
    column: "attendance_required"
    data_type: "tinyint(1) DEFAULT NULL"
  }
  columns: {
    column: "registration_deadline_date"
    data_type: "date DEFAULT NULL"
  }
  columns: {
    column: "registration_link"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "status"
    data_type: "varchar(50) DEFAULT NULL"
  }
  columns: {
    column: "feedback_link"
    data_type: "varchar(255) DEFAULT NULL"
  }
  columns: {
    column: "materials"
    data_type: "text"
  }
}